### ISSUE TITLE
release under an open-source license

### ISSUE THREAD

**Issue by hades** [dpecos/mastodon-comments#1]
Could you please release this code under an open-source license? I might want to make some improvements to it and make sure I can use and publish them. Thanks!

**Comment by jtmusselman** [comment]
I would also appreciate this. I would like to see if I can make this into a hugo module.

**Comment by dpecos** [comment]
Sorry for the delay, I just added the LICENSE file.

If you send me a link to your projects, I'd linked them from the README.
