### ISSUE TITLE
possibility to show likes/boosts on original status?

### ISSUE THREAD

**Issue by kirkpsmith** [dpecos/mastodon-comments#3]
Hey, thanks for your cool webcomponent, I just successfully got it working in my first blog post [here](https://dualpower.supply/posts/motivation-OSHW-RFB/)!

I was wondering how to best extend the code to include the likes/boosts on the original fediverse status linking to the blog post, like done here https://blog.thms.uk/2023/02/mastodon-comments by @nanos (also thank you!)

![image](https://github.com/dpecos/mastodon-comments/assets/7277901/08aa1b24-8a5c-4646-b405-6755a027fac0)

**Comment by dpecos** [comment]
That should not be too hard to accomplish, as those should be the boosts that the root toot (the one matching the ID assigned to your post) is returning.

The only downside is that, as the webcomponent is currently implemented, that API call is lazy, happening only as soon as the user scrolls down, so there will be a small delay until you get the data back.

But aside from that, from the technical point of view, should be just a matter of rendering the counts.

Let me know if you need more tips on this, and if you raise an MR, I'd be more than happy to have a look and merge it!
