### ISSUE TITLE
Javascript detection is useless

### ISSUE THREAD

**Issue by barijaona** [dpecos/mastodon-comments#5]
In your code, there is an attempt to work around a situation where Javascript is not available.

https://github.com/dpecos/mastodon-comments/blob/faf7c03540dce6ea61255a577a2ecaa0f8316876/mastodon-comments.js#L137-L141

This will not function as this part itself should be generated by Javascript…
You'd better remove this part. Anyway, Mastodon web client will require Javascript.

**Comment by dpecos** [comment]
You're right! As this requires JS to be enabled to render the webcomponent, this block will never be displayed.

Removed.
